apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.27 
        ports:
        - containerPort: 3306 
        env:
        - name: MYSQL_ROOT_PASSWORD 
          value: "Rafa81041683!"
        - name: MYSQL_DATABASE
          value: "dbk8s"
        - name: MYSQL_USER 
          value: "root"
        - name: MYSQL_PASSWORD 
          value: "Rafa81041683!"   
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-java
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: backend-java
  template:
    metadata:
      labels:
        app: backend-java
    spec:
      containers:
      - name: backend-java 
        image: rcventura/currency-converter-backend:latest 
        ports:
        - containerPort: 8080 
        env:
        - name: MYSQL_HOST 
          value: "mysql" 
        - name: MYSQL_PORT 
          value: "3306" 
        - name: MYSQL_USER 
          value: "root"
        - name: MYSQL_PASSWORD 
          value: "Rafa81041683!"
           
---
apiVersion: v1
kind: Service
metadata:
  name: backend-java
spec:
  selector:
    app: backend-java
  ports:
    - port: 8080
  type: ClusterIP
